# Generated by Django 5.2.1 on 2025-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=20)),
                ('jurusan', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=15)),
            ],
        ),
    ]
